### ISSUE TITLE
Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse

### ISSUE THREAD

**Issue by mdealiaga** [sifrr/sifrr#381]
Static files are served succesfully from webpack dist and public fodlers via 
```
app.folder('/', "public")
app.file('/', "dist/index.html").folder('/', "dist")
```
However, when refreshing the page and cache (via CTRL+SHIFT+R), the server throws an error.

```
/Users/mdealiaga/code/io-2/node_modules/@sifrr/server/src/server/sendfile.js:165
      res.end();
          ^
Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
Thrown at:
    at /Users/mdealiaga/code/io-2/node_modules/@sifrr/server/src/server/sendfile.js:165:11
    at emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

There is a similar uWebSocket issue report https://github.com/uNetworking/uWebSockets.js/issues/123 where the fix was to "Look over the docs regarding onAborted - you have to track whether the response was aborted or not."
This link to onAborted is https://unetworking.github.io/uWebSockets.js/generated/interfaces/httpresponse.html#onaborted

If I serve only my dist folder, this is not an issue. It only happens when additionally also serving the public folder.

**Comment by aaditya-taparia** [comment]
I think I was using onAborted, but will check again.

**Comment by H0rn0chse** [comment]
Is there any solution to this?
Unfortunately I have the same issue.
